var annotated_dup =
[
    [ "Elevate", "namespaceElevate.html", [
      [ "Editor", "namespaceElevate_1_1Editor.html", [
        [ "AssetBrowserPanel", "classElevate_1_1Editor_1_1AssetBrowserPanel.html", "classElevate_1_1Editor_1_1AssetBrowserPanel" ],
        [ "BrowserPath", "structElevate_1_1Editor_1_1BrowserPath.html", "structElevate_1_1Editor_1_1BrowserPath" ],
        [ "EditorWidget", "classElevate_1_1Editor_1_1EditorWidget.html", "classElevate_1_1Editor_1_1EditorWidget" ],
        [ "FileItem", "structElevate_1_1Editor_1_1FileItem.html", "structElevate_1_1Editor_1_1FileItem" ],
        [ "FileMetadata", "structElevate_1_1Editor_1_1FileMetadata.html", "structElevate_1_1Editor_1_1FileMetadata" ],
        [ "SkyboxEditorWidget", "classElevate_1_1Editor_1_1SkyboxEditorWidget.html", "classElevate_1_1Editor_1_1SkyboxEditorWidget" ],
        [ "StatisticsPanel", "classElevate_1_1Editor_1_1StatisticsPanel.html", "classElevate_1_1Editor_1_1StatisticsPanel" ]
      ] ],
      [ "AddComponentCommand", "classElevate_1_1AddComponentCommand.html", "classElevate_1_1AddComponentCommand" ],
      [ "AddGameobjectCommand", "classElevate_1_1AddGameobjectCommand.html", null ],
      [ "AkBank", "classElevate_1_1AkBank.html", "classElevate_1_1AkBank" ],
      [ "Application", "classElevate_1_1Application.html", "classElevate_1_1Application" ],
      [ "ApplicationArguments", "structElevate_1_1ApplicationArguments.html", "structElevate_1_1ApplicationArguments" ],
      [ "AppRenderEvent", "classElevate_1_1AppRenderEvent.html", "classElevate_1_1AppRenderEvent" ],
      [ "AppTickEvent", "classElevate_1_1AppTickEvent.html", "classElevate_1_1AppTickEvent" ],
      [ "AppUpdateEvent", "classElevate_1_1AppUpdateEvent.html", "classElevate_1_1AppUpdateEvent" ],
      [ "AudioDistanceProbe", "classElevate_1_1AudioDistanceProbe.html", "classElevate_1_1AudioDistanceProbe" ],
      [ "BoundingVolume", "classElevate_1_1BoundingVolume.html", "classElevate_1_1BoundingVolume" ],
      [ "BufferElement", "structElevate_1_1BufferElement.html", "structElevate_1_1BufferElement" ],
      [ "BufferLayout", "classElevate_1_1BufferLayout.html", "classElevate_1_1BufferLayout" ],
      [ "Camera", "classElevate_1_1Camera.html", "classElevate_1_1Camera" ],
      [ "CameraManager", "classElevate_1_1CameraManager.html", null ],
      [ "ColorTag", "structElevate_1_1ColorTag.html", null ],
      [ "Command", "classElevate_1_1Command.html", "classElevate_1_1Command" ],
      [ "CommandManager", "classElevate_1_1CommandManager.html", "classElevate_1_1CommandManager" ],
      [ "Component", "classElevate_1_1Component.html", "classElevate_1_1Component" ],
      [ "ComponentField", "structElevate_1_1ComponentField.html", "structElevate_1_1ComponentField" ],
      [ "ComponentLayout", "classElevate_1_1ComponentLayout.html", "classElevate_1_1ComponentLayout" ],
      [ "ComponentRegistry", "classElevate_1_1ComponentRegistry.html", "classElevate_1_1ComponentRegistry" ],
      [ "Cubemap", "classElevate_1_1Cubemap.html", "classElevate_1_1Cubemap" ],
      [ "DebugLineData", "structElevate_1_1DebugLineData.html", null ],
      [ "DebugRenderer", "classElevate_1_1DebugRenderer.html", null ],
      [ "DebugVertex", "structElevate_1_1DebugVertex.html", null ],
      [ "DefaultShader", "classElevate_1_1DefaultShader.html", null ],
      [ "DeleteGameobjectCommand", "classElevate_1_1DeleteGameobjectCommand.html", "classElevate_1_1DeleteGameobjectCommand" ],
      [ "DirectionalLight", "classElevate_1_1DirectionalLight.html", "classElevate_1_1DirectionalLight" ],
      [ "DisplayNameTag", "structElevate_1_1DisplayNameTag.html", "structElevate_1_1DisplayNameTag" ],
      [ "EditorCamera", "classElevate_1_1EditorCamera.html", "classElevate_1_1EditorCamera" ],
      [ "EditorIconTag", "structElevate_1_1EditorIconTag.html", "structElevate_1_1EditorIconTag" ],
      [ "EngineDataTypeTrait", "structElevate_1_1EngineDataTypeTrait.html", null ],
      [ "EngineDataTypeTrait< bool >", "structElevate_1_1EngineDataTypeTrait_3_01bool_01_4.html", null ],
      [ "EngineDataTypeTrait< float >", "structElevate_1_1EngineDataTypeTrait_3_01float_01_4.html", null ],
      [ "EngineDataTypeTrait< glm::vec2 >", "structElevate_1_1EngineDataTypeTrait_3_01glm_1_1vec2_01_4.html", null ],
      [ "EngineDataTypeTrait< glm::vec3 >", "structElevate_1_1EngineDataTypeTrait_3_01glm_1_1vec3_01_4.html", null ],
      [ "EngineDataTypeTrait< glm::vec4 >", "structElevate_1_1EngineDataTypeTrait_3_01glm_1_1vec4_01_4.html", null ],
      [ "EngineDataTypeTrait< int >", "structElevate_1_1EngineDataTypeTrait_3_01int_01_4.html", null ],
      [ "Event", "classElevate_1_1Event.html", "classElevate_1_1Event" ],
      [ "EventDispatcher", "classElevate_1_1EventDispatcher.html", "classElevate_1_1EventDispatcher" ],
      [ "FieldMeta", "structElevate_1_1FieldMeta.html", "structElevate_1_1FieldMeta" ],
      [ "FlattenTag", "structElevate_1_1FlattenTag.html", null ],
      [ "Framebuffer", "classElevate_1_1Framebuffer.html", "classElevate_1_1Framebuffer" ],
      [ "FramebufferColorAttachment", "structElevate_1_1FramebufferColorAttachment.html", "structElevate_1_1FramebufferColorAttachment" ],
      [ "FramebufferDepthAttachment", "structElevate_1_1FramebufferDepthAttachment.html", "structElevate_1_1FramebufferDepthAttachment" ],
      [ "FramebufferMetadata", "structElevate_1_1FramebufferMetadata.html", "structElevate_1_1FramebufferMetadata" ],
      [ "FramebufferStencilAttachment", "structElevate_1_1FramebufferStencilAttachment.html", null ],
      [ "Frustum", "structElevate_1_1Frustum.html", "structElevate_1_1Frustum" ],
      [ "GameContextEvent", "classElevate_1_1GameContextEvent.html", "classElevate_1_1GameContextEvent" ],
      [ "GameObject", "classElevate_1_1GameObject.html", "classElevate_1_1GameObject" ],
      [ "GlfwInput", "classElevate_1_1GlfwInput.html", "classElevate_1_1GlfwInput" ],
      [ "GlfwWindow", "classElevate_1_1GlfwWindow.html", "classElevate_1_1GlfwWindow" ],
      [ "GraphicsContext", "classElevate_1_1GraphicsContext.html", "classElevate_1_1GraphicsContext" ],
      [ "has_super", "structElevate_1_1has__super.html", null ],
      [ "has_super< T, std::void_t< typename T::Super > >", "structElevate_1_1has__super_3_01T_00_01std_1_1void__t_3_01typename_01T_1_1Super_01_4_01_4.html", null ],
      [ "HideInInspectorTag", "structElevate_1_1HideInInspectorTag.html", null ],
      [ "ImGuiLayer", "classElevate_1_1ImGuiLayer.html", "classElevate_1_1ImGuiLayer" ],
      [ "IndexBuffer", "classElevate_1_1IndexBuffer.html", "classElevate_1_1IndexBuffer" ],
      [ "Input", "classElevate_1_1Input.html", "classElevate_1_1Input" ],
      [ "InputBuffer", "classElevate_1_1InputBuffer.html", "classElevate_1_1InputBuffer" ],
      [ "ISerializable", "classElevate_1_1ISerializable.html", "classElevate_1_1ISerializable" ],
      [ "ITransformable", "classElevate_1_1ITransformable.html", "classElevate_1_1ITransformable" ],
      [ "KeyEvent", "classElevate_1_1KeyEvent.html", "classElevate_1_1KeyEvent" ],
      [ "KeyPressedEvent", "classElevate_1_1KeyPressedEvent.html", "classElevate_1_1KeyPressedEvent" ],
      [ "KeyReleasedEvent", "classElevate_1_1KeyReleasedEvent.html", "classElevate_1_1KeyReleasedEvent" ],
      [ "KeyTypedEvent", "classElevate_1_1KeyTypedEvent.html", "classElevate_1_1KeyTypedEvent" ],
      [ "Layer", "classElevate_1_1Layer.html", "classElevate_1_1Layer" ],
      [ "LayerStack", "classElevate_1_1LayerStack.html", "classElevate_1_1LayerStack" ],
      [ "Light", "classElevate_1_1Light.html", "classElevate_1_1Light" ],
      [ "Log", "classElevate_1_1Log.html", null ],
      [ "LogImpl", "classElevate_1_1LogImpl.html", "classElevate_1_1LogImpl" ],
      [ "MacroCommand", "classElevate_1_1MacroCommand.html", "classElevate_1_1MacroCommand" ],
      [ "Material", "classElevate_1_1Material.html", "classElevate_1_1Material" ],
      [ "MaterialFactory", "classElevate_1_1MaterialFactory.html", "classElevate_1_1MaterialFactory" ],
      [ "MaterialRegistry", "classElevate_1_1MaterialRegistry.html", null ],
      [ "Mesh", "classElevate_1_1Mesh.html", "classElevate_1_1Mesh" ],
      [ "MeshData", "structElevate_1_1MeshData.html", "structElevate_1_1MeshData" ],
      [ "Model", "classElevate_1_1Model.html", "classElevate_1_1Model" ],
      [ "MouseButtonEvent", "classElevate_1_1MouseButtonEvent.html", "classElevate_1_1MouseButtonEvent" ],
      [ "MouseButtonPressedEvent", "classElevate_1_1MouseButtonPressedEvent.html", "classElevate_1_1MouseButtonPressedEvent" ],
      [ "MouseButtonReleasedEvent", "classElevate_1_1MouseButtonReleasedEvent.html", "classElevate_1_1MouseButtonReleasedEvent" ],
      [ "MouseMovedEvent", "classElevate_1_1MouseMovedEvent.html", "classElevate_1_1MouseMovedEvent" ],
      [ "MouseScrolledEvent", "classElevate_1_1MouseScrolledEvent.html", "classElevate_1_1MouseScrolledEvent" ],
      [ "OpenGLContext", "classElevate_1_1OpenGLContext.html", "classElevate_1_1OpenGLContext" ],
      [ "OpenGLFrameBuffer", "classElevate_1_1OpenGLFrameBuffer.html", "classElevate_1_1OpenGLFrameBuffer" ],
      [ "OpenGLIndexBuffer", "classElevate_1_1OpenGLIndexBuffer.html", "classElevate_1_1OpenGLIndexBuffer" ],
      [ "OpenGLRendererAPI", "classElevate_1_1OpenGLRendererAPI.html", "classElevate_1_1OpenGLRendererAPI" ],
      [ "OpenGLShader", "classElevate_1_1OpenGLShader.html", "classElevate_1_1OpenGLShader" ],
      [ "OpenGLTexture", "classElevate_1_1OpenGLTexture.html", "classElevate_1_1OpenGLTexture" ],
      [ "OpenGLVertexArray", "classElevate_1_1OpenGLVertexArray.html", "classElevate_1_1OpenGLVertexArray" ],
      [ "OpenGLVertexBuffer", "classElevate_1_1OpenGLVertexBuffer.html", "classElevate_1_1OpenGLVertexBuffer" ],
      [ "ParentFieldsHelper", "structElevate_1_1ParentFieldsHelper.html", null ],
      [ "ParentFieldsHelper< T, true >", "structElevate_1_1ParentFieldsHelper_3_01T_00_01true_01_4.html", null ],
      [ "PathResolver", "classElevate_1_1PathResolver.html", null ],
      [ "Plane", "structElevate_1_1Plane.html", "structElevate_1_1Plane" ],
      [ "PointLight", "classElevate_1_1PointLight.html", "classElevate_1_1PointLight" ],
      [ "ReadOnlyTag", "structElevate_1_1ReadOnlyTag.html", null ],
      [ "RemoveComponentCommand", "classElevate_1_1RemoveComponentCommand.html", "classElevate_1_1RemoveComponentCommand" ],
      [ "RenderBucket", "classElevate_1_1RenderBucket.html", "classElevate_1_1RenderBucket" ],
      [ "RenderCommand", "structElevate_1_1RenderCommand.html", "structElevate_1_1RenderCommand" ],
      [ "RenderCommandQueue", "classElevate_1_1RenderCommandQueue.html", "classElevate_1_1RenderCommandQueue" ],
      [ "Renderer", "classElevate_1_1Renderer.html", null ],
      [ "RendererAPI", "classElevate_1_1RendererAPI.html", "classElevate_1_1RendererAPI" ],
      [ "RenderState", "structElevate_1_1RenderState.html", "structElevate_1_1RenderState" ],
      [ "Rigidbody", "classElevate_1_1Rigidbody.html", "classElevate_1_1Rigidbody" ],
      [ "RigidbodyData", "structElevate_1_1RigidbodyData.html", "structElevate_1_1RigidbodyData" ],
      [ "Scene", "classElevate_1_1Scene.html", "classElevate_1_1Scene" ],
      [ "SceneLayer", "classElevate_1_1SceneLayer.html", "classElevate_1_1SceneLayer" ],
      [ "SceneLighting", "classElevate_1_1SceneLighting.html", "classElevate_1_1SceneLighting" ],
      [ "SceneManager", "classElevate_1_1SceneManager.html", null ],
      [ "Shader", "classElevate_1_1Shader.html", "classElevate_1_1Shader" ],
      [ "ShaderManager", "classElevate_1_1ShaderManager.html", null ],
      [ "SoundEngine", "classElevate_1_1SoundEngine.html", "classElevate_1_1SoundEngine" ],
      [ "SphereBoundingVolume", "classElevate_1_1SphereBoundingVolume.html", "classElevate_1_1SphereBoundingVolume" ],
      [ "SurfaceMaterial", "structElevate_1_1SurfaceMaterial.html", "structElevate_1_1SurfaceMaterial" ],
      [ "Texture", "classElevate_1_1Texture.html", "classElevate_1_1Texture" ],
      [ "TextureLoadResult", "structElevate_1_1TextureLoadResult.html", "structElevate_1_1TextureLoadResult" ],
      [ "TextureManager", "classElevate_1_1TextureManager.html", "classElevate_1_1TextureManager" ],
      [ "TextureMetadata", "structElevate_1_1TextureMetadata.html", "structElevate_1_1TextureMetadata" ],
      [ "TextureMetadataBuilder", "structElevate_1_1TextureMetadataBuilder.html", "structElevate_1_1TextureMetadataBuilder" ],
      [ "Time", "classElevate_1_1Time.html", "classElevate_1_1Time" ],
      [ "TooltipTag", "structElevate_1_1TooltipTag.html", "structElevate_1_1TooltipTag" ],
      [ "Transform", "classElevate_1_1Transform.html", "classElevate_1_1Transform" ],
      [ "UUID", "structElevate_1_1UUID.html", null ],
      [ "Vertex", "structElevate_1_1Vertex.html", "structElevate_1_1Vertex" ],
      [ "VertexArray", "classElevate_1_1VertexArray.html", "classElevate_1_1VertexArray" ],
      [ "VertexBuffer", "classElevate_1_1VertexBuffer.html", "classElevate_1_1VertexBuffer" ],
      [ "WAAPIClient", "classElevate_1_1WAAPIClient.html", "classElevate_1_1WAAPIClient" ],
      [ "Window", "classElevate_1_1Window.html", "classElevate_1_1Window" ],
      [ "WindowCloseEvent", "classElevate_1_1WindowCloseEvent.html", "classElevate_1_1WindowCloseEvent" ],
      [ "WindowData", "structElevate_1_1WindowData.html", "structElevate_1_1WindowData" ],
      [ "WindowFocusEvent", "classElevate_1_1WindowFocusEvent.html", "classElevate_1_1WindowFocusEvent" ],
      [ "WindowProps", "structElevate_1_1WindowProps.html", "structElevate_1_1WindowProps" ],
      [ "WindowResizeEvent", "classElevate_1_1WindowResizeEvent.html", "classElevate_1_1WindowResizeEvent" ],
      [ "WwiseFileDataSource", "classElevate_1_1WwiseFileDataSource.html", "classElevate_1_1WwiseFileDataSource" ]
    ] ],
    [ "flxml", "namespaceflxml.html", [
      [ "xml_node", "classflxml_1_1xml__node.html", null ]
    ] ],
    [ "EECategory", "classEECategory.html", "classEECategory" ],
    [ "EEObject", "classEEObject.html", "classEEObject" ],
    [ "WwiseAuxBus", "structWwiseAuxBus.html", null ],
    [ "WwiseBus", "structWwiseBus.html", null ],
    [ "WwiseDataSource", "classWwiseDataSource.html", "classWwiseDataSource" ],
    [ "WwiseEvent", "structWwiseEvent.html", "structWwiseEvent" ],
    [ "WwiseGameParameter", "structWwiseGameParameter.html", "structWwiseGameParameter" ],
    [ "WwiseItem", "structWwiseItem.html", "structWwiseItem" ],
    [ "WwiseSoundbank", "structWwiseSoundbank.html", "structWwiseSoundbank" ],
    [ "WwiseState", "structWwiseState.html", "structWwiseState" ],
    [ "WwiseStateGroup", "structWwiseStateGroup.html", null ],
    [ "WwiseSwitch", "structWwiseSwitch.html", "structWwiseSwitch" ],
    [ "WwiseSwitchGroup", "structWwiseSwitchGroup.html", null ]
];