# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debugstaticcrt_win64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

INCLUDES += -IElevateEngine/vendor/_config_headers -IElevateEngine/vendor/_config_headers/assimp -IElevateEngine/vendor/assimp/include -ID:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase -ID:/Audiokinetic/Wwise2025.1.5.9095/SDK/include -ID:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/3rdParty/subprojects/rapidjson/include
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debugstaticcrt_win64)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/DebugStaticCRT-windows-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/WwiseProjectDatabase.lib
OBJDIR = Build/bin-int/DebugStaticCRT-windows-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),debugstaticcrt_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/DebugStaticCRT-linux-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/DebugStaticCRT-linux-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),debugstaticcrt_web)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/DebugStaticCRT-emscripten-wasm32/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/DebugStaticCRT-emscripten-wasm32/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),releasestaticcrt)_win64)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/ReleaseStaticCRT)-windows-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/WwiseProjectDatabase.lib
OBJDIR = Build/bin-int/ReleaseStaticCRT)-windows-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),releasestaticcrt)_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/ReleaseStaticCRT)-linux-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/ReleaseStaticCRT)-linux-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),releasestaticcrt)_web)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/ReleaseStaticCRT)-emscripten-wasm32/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/ReleaseStaticCRT)-emscripten-wasm32/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),debug_win64)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/Debug-windows-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/WwiseProjectDatabase.lib
OBJDIR = Build/bin-int/Debug-windows-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),debug_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/Debug-linux-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/Debug-linux-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),debug_web)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/Debug-emscripten-wasm32/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/Debug-emscripten-wasm32/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -g
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -g -std=c++20
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),release_win64)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/Release-windows-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/WwiseProjectDatabase.lib
OBJDIR = Build/bin-int/Release-windows-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),release_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/Release-linux-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/Release-linux-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),release_web)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/Release-emscripten-wasm32/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/Release-emscripten-wasm32/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS)

else ifeq ($(config),releasestaticcrt_win64)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/ReleaseStaticCRT-windows-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/WwiseProjectDatabase.lib
OBJDIR = Build/bin-int/ReleaseStaticCRT-windows-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),releasestaticcrt_linux)
ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/ReleaseStaticCRT-linux-x86_64/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/ReleaseStaticCRT-linux-x86_64/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -s

else ifeq ($(config),releasestaticcrt_web)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
TARGETDIR = Build/bin/ReleaseStaticCRT-emscripten-wasm32/WwiseProjectDatabase
TARGET = $(TARGETDIR)/libWwiseProjectDatabase.a
OBJDIR = Build/bin-int/ReleaseStaticCRT-emscripten-wasm32/WwiseProjectDatabase
DEFINES += -DTESTING_WWISE_PROJECT_DATABASE -DEE_USES_WWISEPROJECTDATABASE -DWIN32_LEAN_AND_MEAN -DWWISE_DB_STANDARD_TYPES -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -O2
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -O2 -std=c++20
ALL_LDFLAGS += $(LDFLAGS)

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/WwiseAnyRef.o
GENERATED += $(OBJDIR)/WwiseDataStructure.o
GENERATED += $(OBJDIR)/WwiseDatabaseIdentifiers.o
GENERATED += $(OBJDIR)/WwiseDirectoryVisitor.o
GENERATED += $(OBJDIR)/WwiseGeneratedFiles.o
GENERATED += $(OBJDIR)/WwiseMetadataAcousticTexture.o
GENERATED += $(OBJDIR)/WwiseMetadataActionEntries.o
GENERATED += $(OBJDIR)/WwiseMetadataBasicReference.o
GENERATED += $(OBJDIR)/WwiseMetadataBus.o
GENERATED += $(OBJDIR)/WwiseMetadataDialogue.o
GENERATED += $(OBJDIR)/WwiseMetadataEvent.o
GENERATED += $(OBJDIR)/WwiseMetadataExternalSource.o
GENERATED += $(OBJDIR)/WwiseMetadataGameParameter.o
GENERATED += $(OBJDIR)/WwiseMetadataGroupValueReference.o
GENERATED += $(OBJDIR)/WwiseMetadataLanguage.o
GENERATED += $(OBJDIR)/WwiseMetadataLoadable.o
GENERATED += $(OBJDIR)/WwiseMetadataLoader.o
GENERATED += $(OBJDIR)/WwiseMetadataMedia.o
GENERATED += $(OBJDIR)/WwiseMetadataPlatform.o
GENERATED += $(OBJDIR)/WwiseMetadataPlatformInfo.o
GENERATED += $(OBJDIR)/WwiseMetadataPlugin.o
GENERATED += $(OBJDIR)/WwiseMetadataPluginGroup.o
GENERATED += $(OBJDIR)/WwiseMetadataPluginInfo.o
GENERATED += $(OBJDIR)/WwiseMetadataPluginLib.o
GENERATED += $(OBJDIR)/WwiseMetadataProject.o
GENERATED += $(OBJDIR)/WwiseMetadataProjectInfo.o
GENERATED += $(OBJDIR)/WwiseMetadataRootFile.o
GENERATED += $(OBJDIR)/WwiseMetadataRootPaths.o
GENERATED += $(OBJDIR)/WwiseMetadataSettings.o
GENERATED += $(OBJDIR)/WwiseMetadataSoundBank.o
GENERATED += $(OBJDIR)/WwiseMetadataSoundBanksInfo.o
GENERATED += $(OBJDIR)/WwiseMetadataState.o
GENERATED += $(OBJDIR)/WwiseMetadataStateGroup.o
GENERATED += $(OBJDIR)/WwiseMetadataSwitch.o
GENERATED += $(OBJDIR)/WwiseMetadataSwitchContainer.o
GENERATED += $(OBJDIR)/WwiseMetadataSwitchGroup.o
GENERATED += $(OBJDIR)/WwiseMetadataSwitchValue.o
GENERATED += $(OBJDIR)/WwiseMetadataTrigger.o
GENERATED += $(OBJDIR)/WwiseProjectDatabase.o
GENERATED += $(OBJDIR)/WwiseProjectDatabaseLoggingUtils.o
GENERATED += $(OBJDIR)/WwiseProjectDatabaseStandardLogging.o
GENERATED += $(OBJDIR)/WwiseRefAcousticTexture.o
GENERATED += $(OBJDIR)/WwiseRefAudioDevice.o
GENERATED += $(OBJDIR)/WwiseRefAuxBus.o
GENERATED += $(OBJDIR)/WwiseRefBus.o
GENERATED += $(OBJDIR)/WwiseRefCustomPlugin.o
GENERATED += $(OBJDIR)/WwiseRefDialogueArgument.o
GENERATED += $(OBJDIR)/WwiseRefDialogueEvent.o
GENERATED += $(OBJDIR)/WwiseRefEvent.o
GENERATED += $(OBJDIR)/WwiseRefExternalSource.o
GENERATED += $(OBJDIR)/WwiseRefGameParameter.o
GENERATED += $(OBJDIR)/WwiseRefLanguage.o
GENERATED += $(OBJDIR)/WwiseRefMedia.o
GENERATED += $(OBJDIR)/WwiseRefPlatform.o
GENERATED += $(OBJDIR)/WwiseRefPlatformInfo.o
GENERATED += $(OBJDIR)/WwiseRefPluginInfo.o
GENERATED += $(OBJDIR)/WwiseRefPluginLib.o
GENERATED += $(OBJDIR)/WwiseRefPluginShareSet.o
GENERATED += $(OBJDIR)/WwiseRefProjectInfo.o
GENERATED += $(OBJDIR)/WwiseRefRootFile.o
GENERATED += $(OBJDIR)/WwiseRefSoundBank.o
GENERATED += $(OBJDIR)/WwiseRefSoundBanksInfo.o
GENERATED += $(OBJDIR)/WwiseRefState.o
GENERATED += $(OBJDIR)/WwiseRefStateGroup.o
GENERATED += $(OBJDIR)/WwiseRefSwitch.o
GENERATED += $(OBJDIR)/WwiseRefSwitchContainer.o
GENERATED += $(OBJDIR)/WwiseRefSwitchGroup.o
GENERATED += $(OBJDIR)/WwiseRefTrigger.o
GENERATED += $(OBJDIR)/stdafx.o
OBJECTS += $(OBJDIR)/WwiseAnyRef.o
OBJECTS += $(OBJDIR)/WwiseDataStructure.o
OBJECTS += $(OBJDIR)/WwiseDatabaseIdentifiers.o
OBJECTS += $(OBJDIR)/WwiseDirectoryVisitor.o
OBJECTS += $(OBJDIR)/WwiseGeneratedFiles.o
OBJECTS += $(OBJDIR)/WwiseMetadataAcousticTexture.o
OBJECTS += $(OBJDIR)/WwiseMetadataActionEntries.o
OBJECTS += $(OBJDIR)/WwiseMetadataBasicReference.o
OBJECTS += $(OBJDIR)/WwiseMetadataBus.o
OBJECTS += $(OBJDIR)/WwiseMetadataDialogue.o
OBJECTS += $(OBJDIR)/WwiseMetadataEvent.o
OBJECTS += $(OBJDIR)/WwiseMetadataExternalSource.o
OBJECTS += $(OBJDIR)/WwiseMetadataGameParameter.o
OBJECTS += $(OBJDIR)/WwiseMetadataGroupValueReference.o
OBJECTS += $(OBJDIR)/WwiseMetadataLanguage.o
OBJECTS += $(OBJDIR)/WwiseMetadataLoadable.o
OBJECTS += $(OBJDIR)/WwiseMetadataLoader.o
OBJECTS += $(OBJDIR)/WwiseMetadataMedia.o
OBJECTS += $(OBJDIR)/WwiseMetadataPlatform.o
OBJECTS += $(OBJDIR)/WwiseMetadataPlatformInfo.o
OBJECTS += $(OBJDIR)/WwiseMetadataPlugin.o
OBJECTS += $(OBJDIR)/WwiseMetadataPluginGroup.o
OBJECTS += $(OBJDIR)/WwiseMetadataPluginInfo.o
OBJECTS += $(OBJDIR)/WwiseMetadataPluginLib.o
OBJECTS += $(OBJDIR)/WwiseMetadataProject.o
OBJECTS += $(OBJDIR)/WwiseMetadataProjectInfo.o
OBJECTS += $(OBJDIR)/WwiseMetadataRootFile.o
OBJECTS += $(OBJDIR)/WwiseMetadataRootPaths.o
OBJECTS += $(OBJDIR)/WwiseMetadataSettings.o
OBJECTS += $(OBJDIR)/WwiseMetadataSoundBank.o
OBJECTS += $(OBJDIR)/WwiseMetadataSoundBanksInfo.o
OBJECTS += $(OBJDIR)/WwiseMetadataState.o
OBJECTS += $(OBJDIR)/WwiseMetadataStateGroup.o
OBJECTS += $(OBJDIR)/WwiseMetadataSwitch.o
OBJECTS += $(OBJDIR)/WwiseMetadataSwitchContainer.o
OBJECTS += $(OBJDIR)/WwiseMetadataSwitchGroup.o
OBJECTS += $(OBJDIR)/WwiseMetadataSwitchValue.o
OBJECTS += $(OBJDIR)/WwiseMetadataTrigger.o
OBJECTS += $(OBJDIR)/WwiseProjectDatabase.o
OBJECTS += $(OBJDIR)/WwiseProjectDatabaseLoggingUtils.o
OBJECTS += $(OBJDIR)/WwiseProjectDatabaseStandardLogging.o
OBJECTS += $(OBJDIR)/WwiseRefAcousticTexture.o
OBJECTS += $(OBJDIR)/WwiseRefAudioDevice.o
OBJECTS += $(OBJDIR)/WwiseRefAuxBus.o
OBJECTS += $(OBJDIR)/WwiseRefBus.o
OBJECTS += $(OBJDIR)/WwiseRefCustomPlugin.o
OBJECTS += $(OBJDIR)/WwiseRefDialogueArgument.o
OBJECTS += $(OBJDIR)/WwiseRefDialogueEvent.o
OBJECTS += $(OBJDIR)/WwiseRefEvent.o
OBJECTS += $(OBJDIR)/WwiseRefExternalSource.o
OBJECTS += $(OBJDIR)/WwiseRefGameParameter.o
OBJECTS += $(OBJDIR)/WwiseRefLanguage.o
OBJECTS += $(OBJDIR)/WwiseRefMedia.o
OBJECTS += $(OBJDIR)/WwiseRefPlatform.o
OBJECTS += $(OBJDIR)/WwiseRefPlatformInfo.o
OBJECTS += $(OBJDIR)/WwiseRefPluginInfo.o
OBJECTS += $(OBJDIR)/WwiseRefPluginLib.o
OBJECTS += $(OBJDIR)/WwiseRefPluginShareSet.o
OBJECTS += $(OBJDIR)/WwiseRefProjectInfo.o
OBJECTS += $(OBJDIR)/WwiseRefRootFile.o
OBJECTS += $(OBJDIR)/WwiseRefSoundBank.o
OBJECTS += $(OBJDIR)/WwiseRefSoundBanksInfo.o
OBJECTS += $(OBJDIR)/WwiseRefState.o
OBJECTS += $(OBJDIR)/WwiseRefStateGroup.o
OBJECTS += $(OBJDIR)/WwiseRefSwitch.o
OBJECTS += $(OBJDIR)/WwiseRefSwitchContainer.o
OBJECTS += $(OBJDIR)/WwiseRefSwitchGroup.o
OBJECTS += $(OBJDIR)/WwiseRefTrigger.o
OBJECTS += $(OBJDIR)/stdafx.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking WwiseProjectDatabase
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning WwiseProjectDatabase
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/WwiseProjectDatabase.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseProjectDatabaseLoggingUtils.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/AdapterTypes/Standard/WwiseProjectDatabaseLoggingUtils.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseProjectDatabaseStandardLogging.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/AdapterTypes/Standard/WwiseProjectDatabaseStandardLogging.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataAcousticTexture.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataAcousticTexture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataActionEntries.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataActionEntries.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataBasicReference.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataBasicReference.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataBus.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataBus.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataDialogue.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataDialogue.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataEvent.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataEvent.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataExternalSource.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataExternalSource.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataGameParameter.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataGameParameter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataGroupValueReference.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataGroupValueReference.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataLanguage.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataLanguage.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataLoadable.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataLoadable.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataLoader.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataLoader.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataMedia.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataMedia.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataPlatform.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataPlatform.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataPlatformInfo.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataPlatformInfo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataPlugin.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataPlugin.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataPluginGroup.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataPluginGroup.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataPluginInfo.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataPluginInfo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataPluginLib.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataPluginLib.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataProject.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataProject.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataProjectInfo.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataProjectInfo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataRootFile.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataRootFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataRootPaths.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataRootPaths.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataSettings.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataSettings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataSoundBank.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataSoundBank.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataSoundBanksInfo.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataSoundBanksInfo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataState.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataStateGroup.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataStateGroup.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataSwitch.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataSwitch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataSwitchContainer.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataSwitchContainer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataSwitchGroup.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataSwitchGroup.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataSwitchValue.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataSwitchValue.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseMetadataTrigger.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Metadata/WwiseMetadataTrigger.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseAnyRef.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseAnyRef.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefAcousticTexture.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefAcousticTexture.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefAudioDevice.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefAudioDevice.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefAuxBus.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefAuxBus.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefBus.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefBus.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefCustomPlugin.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefCustomPlugin.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefDialogueArgument.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefDialogueArgument.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefDialogueEvent.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefDialogueEvent.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefEvent.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefEvent.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefExternalSource.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefExternalSource.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefGameParameter.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefGameParameter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefLanguage.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefLanguage.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefMedia.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefMedia.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefPlatform.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefPlatform.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefPlatformInfo.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefPlatformInfo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefPluginInfo.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefPluginInfo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefPluginLib.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefPluginLib.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefPluginShareSet.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefPluginShareSet.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefProjectInfo.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefProjectInfo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefRootFile.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefRootFile.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefSoundBank.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefSoundBank.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefSoundBanksInfo.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefSoundBanksInfo.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefState.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefState.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefStateGroup.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefStateGroup.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefSwitch.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefSwitch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefSwitchContainer.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefSwitchContainer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefSwitchGroup.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefSwitchGroup.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseRefTrigger.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/Ref/WwiseRefTrigger.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseDataStructure.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/WwiseDataStructure.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseDatabaseIdentifiers.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/WwiseDatabaseIdentifiers.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseDirectoryVisitor.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/WwiseDirectoryVisitor.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WwiseGeneratedFiles.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/WwiseProjectDatabase/WwiseGeneratedFiles.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/stdafx.o: D:/Audiokinetic/Wwise2025.1.5.9095/SDK/samples/WwiseProjectDatabase/stdafx.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif