#pragma once

// Button (Xbox)
#define EE_GAMEPAD_BUTTON_A               0
#define EE_GAMEPAD_BUTTON_B               1
#define EE_GAMEPAD_BUTTON_X               2
#define EE_GAMEPAD_BUTTON_Y               3
#define EE_GAMEPAD_BUTTON_LEFT_BUMPER     4
#define EE_GAMEPAD_BUTTON_RIGHT_BUMPER    5
#define EE_GAMEPAD_BUTTON_BACK            6
#define EE_GAMEPAD_BUTTON_START           7
#define EE_GAMEPAD_BUTTON_GUIDE           8
#define EE_GAMEPAD_BUTTON_LEFT_THUMB      9
#define EE_GAMEPAD_BUTTON_RIGHT_THUMB     10
#define EE_GAMEPAD_BUTTON_DPAD_UP         11
#define EE_GAMEPAD_BUTTON_DPAD_RIGHT      12
#define EE_GAMEPAD_BUTTON_DPAD_DOWN       13
#define EE_GAMEPAD_BUTTON_DPAD_LEFT       14
#define EE_GAMEPAD_BUTTON_LAST            EE_GAMEPAD_BUTTON_DPAD_LEFT

// Button (Playstation)
#define EE_GAMEPAD_BUTTON_CROSS       EE_GAMEPAD_BUTTON_A
#define EE_GAMEPAD_BUTTON_CIRCLE      EE_GAMEPAD_BUTTON_B
#define EE_GAMEPAD_BUTTON_SQUARE      EE_GAMEPAD_BUTTON_X
#define EE_GAMEPAD_BUTTON_TRIANGLE    EE_GAMEPAD_BUTTON_Y

// Axis
#define EE_GAMEPAD_AXIS_LEFT_X        0
#define EE_GAMEPAD_AXIS_LEFT_Y        1
#define EE_GAMEPAD_AXIS_RIGHT_X       2
#define EE_GAMEPAD_AXIS_RIGHT_Y       3
#define EE_GAMEPAD_AXIS_LEFT_TRIGGER  4
#define EE_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define EE_GAMEPAD_AXIS_LAST          EE_GAMEPAD_AXIS_RIGHT_TRIGGER

// Hat
#define EE_GAMEPAD_HAT_CENTERED           0
#define EE_GAMEPAD_HAT_UP                 1
#define EE_GAMEPAD_HAT_RIGHT              2
#define EE_GAMEPAD_HAT_DOWN               4
#define EE_GAMEPAD_HAT_LEFT               8
#define EE_GAMEPAD_HAT_RIGHT_UP           (EE_GAMEPAD_HAT_RIGHT | EE_GAMEPAD_HAT_UP)
#define EE_GAMEPAD_HAT_RIGHT_DOWN         (EE_GAMEPAD_HAT_RIGHT | EE_GAMEPAD_HAT_DOWN)
#define EE_GAMEPAD_HAT_LEFT_UP            (EE_GAMEPAD_HAT_LEFT  | EE_GAMEPAD_HAT_UP)
#define EE_GAMEPAD_HAT_LEFT_DOWN          (EE_GAMEPAD_HAT_LEFT  | EE_GAMEPAD_HAT_DOWN)