name: Build Elevate Engine

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
      - name: Cleanup Project
        run: |
          rm -rf Build/ bin/ bin-int/

      - name: Generate Projects (Premake)
        run: |
          chmod +x vendor/premake/premake5-linux
          ./vendor/premake/premake5-linux --os=linux gmake2 
      - name: Print Makefile
        run: cat Makefile

      - name: Compile
        run: |
           grep '^[^#[:space:]].*:' Makefile
           make config=editor_debug -j$(nproc)

      - name: Run tests
        run: ./Build/bin/Editor_Debug-linux-x86_64/ElevateEngine-Tests/ElevateEngine-Tests -r junit -o junit-results.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-linux
          path: junit-results.xml

  build-windows:
    runs-on: windows-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Generate Projects (Premake)
        run: ./vendor/premake/premake5.exe --os=windows vs2022

      - name: Compile
        run: msbuild ElevateEngine.sln /p:Configuration="Editor_Debug"

      - name: Run tests
        run: .\Build\bin\Editor_Debug-windows-x86_64\ElevateEngine-Tests\ElevateEngine-Tests -r junit -o junit-results.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-windows
          path: junit-results.xml

  build-web-windows-ninja:  
    runs-on: windows-latest
    steps:
      - name : Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          version: 1.12.1

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 'latest'

      - name: Generate Projects (Premake)
        run: ./vendor/premake/premake5.exe --os=emscripten ninja

      - name: Compile
        run: ninja Editor_Debug
