name: Build Elevate Engine

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

      - name: Cleanup Project
        run: |
          rm -rf Build/ bin/ bin-int/

      - name: Generate Projects (Premake)
        run: |
          chmod +x vendor/premake/premake5-linux
          ./vendor/premake/premake5-linux gmake2

      - name: Compile
        run: |
           grep '^[^#[:space:]].*:' Makefile
           make config=Editor_Debug_Linux -j$(nproc)
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Generate Projects (Premake)
        run: ./vendor/premake/premake5.exe vs2022

      - name: Compile
        run: msbuild ElevateEngine.sln /p:Configuration="Editor Debug"
