name: IWYU Automated Report

on: [push, workflow_dispatch]

jobs:
  iwyu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate Compile Commands
        run: |
          chmod +x ./vendor/premake/premake5-linux
        
          ./vendor/premake/premake5-linux export-compile-commands
          cp compile_commands/editor_debug.json compile_commands.json

          sed -i 's/-MMD//g' compile_commands.json
          sed -i 's/-MP//g' compile_commands.json

          sed -i 's/"command": "cc/"command": "cc -std=c++20/g' compile_commands.json

          jq -r '.[].directory' compile_commands.json | xargs mkdir -p

      - name: Run Include What You Use
        uses: muttleyxd/clang-tools-static-binaries@master
        with:
          command: iwyu
          args: -p . -- -std=c++20