name: IWYU Automated Report

on: [push, workflow_dispatch]

jobs:
  iwyu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install IWYU and JQ
        run: |
          sudo apt-get update
          sudo apt-get install -y iwyu jq

      - name: Generate Compile Commands
        run: |
          chmod +x ./vendor/premake/premake5-linux

          ./vendor/premake/premake5-linux export-compile-commands
          cp compile_commands/editor_debug.json compile_commands.json

          sed -i 's/-MMD//g' compile_commands.json
          sed -i 's/-MP//g' compile_commands.json
          sed -i 's/"command": "cc/"command": "cc -std=c++20/g' compile_commands.json

          jq '[.[] | select(.file | contains("ElevateEngine/src"))]' compile_commands.json > filtered_commands.json
          mv filtered_commands.json compile_commands.json

          jq -r '.[].directory' compile_commands.json | xargs mkdir -p

      - name: Run Include What You Use
        run: |
          if command -v iwyu_tool > /dev/null; then
            iwyu_tool -p . > iwyu_report.txt 2>&1 || true
          else
            include-what-you-use -p . > iwyu_report.txt 2>&1 || true
          fi

      - name: Print and Filter IWYU Report
        run: |
          echo "===================================================="
          echo " IWYU REPORT (ELEVATE ENGINE)"
          echo "===================================================="

          grep -v "error: no such file or directory" iwyu_report.txt | \
          grep -v "vendor/" | \
          grep -v "error: expected a clang compiler command" | \
          grep -v "^$" | \
          sed '/^---/!b;n;/^[[:space:]]*$/d' > clean_report.txt

          # On affiche le résultat
          cat clean_report.txt || echo "No suggestions found."
          
          grep -E "ElevateEngine/src|should add|should remove|forward declare|---|^#" || echo "No suggestions found."
          echo "===================================================="